### PR TITLE
WIP: update to ipyleaflet 0.8.4

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by JohanMabille** [comment]
I think this one can be closed no since xleaflet has been upgraded to ipyleaflet 0.9.

**Comment by SylvainCorlay** [comment]
Probably not

**Comment by SylvainCorlay** [comment]
I was merely changing version numbers so that it *works* with the latest ipyleaflet and xeus, but this PR adds the missing widgets.

**Comment by SylvainCorlay** [comment]
Closing as superseeded by rebased PR.

**Pull request closed without merging**
